FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ../NotificationCalendar.Api/NotificationCalendar.Api.csproj NotificationCalendar.Api/
COPY ../NotificationCalendar.Persistence/NotificationCalendar.Persistence.csproj NotificationCalendar.Persistence/
COPY ../NotificationCalendar.Abstractions/NotificationCalendar.Abstractions.csproj NotificationCalendar.Abstractions/
COPY ../NotificationCalendar.Common/NotificationCalendar.Common.csproj NotificationCalendar.Common/
COPY ../NotificationCalendar.Domain/NotificationCalendar.Domain.csproj NotificationCalendar.Domain/
COPY ../NotificationCalendar.Contracts/NotificationCalendar.Contracts.csproj NotificationCalendar.Contracts/
COPY ../NotificationCalendar.Application/NotificationCalendar.Application.csproj NotificationCalendar.Application/

RUN dotnet restore "NotificationCalendar.Api/NotificationCalendar.Api.csproj"

COPY ../ .

WORKDIR "/src/NotificationCalendar.Api"

RUN dotnet build "NotificationCalendar.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "NotificationCalendar.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

